name: Deploy Roblox Game

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foreman
        run: |
          # Install Rust (required for foreman)
          sudo apt-get update
          sudo apt-get install -y rustc

          # Install Foreman using Cargo (Rust's package manager)
          cargo install foreman

      - name: Install dependencies via Foreman
        run: |
          # Run foreman install to install tools defined in foreman.toml
          foreman install

      - name: Run Rojo deploy
        run: |
          rojo push --place-id ${{ secrets.ROBUX_PLACE_ID }} --api-key ${{ secrets.ROBUX_API_KEY }}

      - name: Post-deployment cleanup
        run: |
          # Any post-deployment steps you need
          echo "Deployment complete"